name: build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: masarakki/docker-alias@v3
        with:
          image: vvakame/review:2.5
          commands: review-pdfmaker
      - run: rm `bundle exec which review-pdfmaker`
      - run: bundle exec rake pdf
      - uses: actions/upload-artifact@v1
        with:
          name: book
          path: book.pdf
